---
title: "Makerspace Word Frequencies"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(tokenizers)
library(tm)

data <- read.csv("MakerspaceSample.csv")
dictionary <- paste(data$Description, collapse = ' ')
dictionary <- unlist(tokenize_words(tolower(dictionary)))
stop_words <- stopwords("en")
filtered_dictionary <- dictionary[!(dictionary %in% stop_words)]
```

```{r}
#Top 30 words overall
word_frequencies <- table(filtered_dictionary)
word_frequencies <- sort(word_frequencies, decreasing = TRUE)
top_30 <- head(word_frequencies, 30)
print(top_30)
```

```{r}
#Top 30 words - nonprofit only
nonprofit <- data[data$Nonprofit_Commercial == "N",]
nonprofit <- paste(nonprofit$Description, collapse = ' ')
nonprofit <- unlist(tokenize_words(tolower(nonprofit)))
filtered_nonprofit <- nonprofit[!(nonprofit %in% stop_words)]
total_nonprofit <- length(filtered_nonprofit)
print(total_nonprofit)
word_frequencies <- table(filtered_nonprofit)
word_frequencies <- sort(word_frequencies, decreasing = TRUE)
top_30 <- head(word_frequencies, 30)
print(top_30)
```

```{r}
#Top 30 words - commercial only
commercial <- data[data$Nonprofit_Commercial == "C",]
commercial <- paste(commercial$Description, collapse = ' ')
commercial <- unlist(tokenize_words(tolower(commercial)))
filtered_commercial <- commercial[!(commercial %in% stop_words)]
total_commercial <- length(filtered_commercial)
print(total_commercial)
word_frequencies <- table(filtered_commercial)
word_frequencies <- sort(word_frequencies, decreasing = TRUE)
top_30 <- head(word_frequencies, 30)
print(top_30)
```
```{r}
#Socioemotional coding
community <- c("collaboration", "community", "team", "unity", "collective", "networking", "support", "together", "teamwork", "shared")
dei <- c("diversity", "equity", "inclusion", "everyone", "anyone", "all kinds", "for all", "supportive", "representation", "equal", "empowerment", "empower", "inclusive", "access", "accessibility", "belonging", "embrace differences", "embracing differences", "variety of voices", "fair")
personal_growth <- c("empower", "empowerment", "autonomy", "agency", "self-efficacy", "confidence", "confident", "motivation", "develop", "goal", "grow", "growth", "potential", "goals", "mastery")
```

```{r}
#Instrumental coding
creativity <- c("creativity", "creative", "creator", "creators", "imagine", "imagination", "new")
skills <- c("skill", "skills", "learn", "learning", "problem solving", "employment", "job", "jobs")
entrepreneurship <- c("entrepreneur", "entrepreneurs", "entrepreneurship", "innovation", "innovator", "innovators", "business", "owner", "opportunity", "accelerator", "accelerating")
prototype <- c("prototype", "prototypes", "prototyping")
economy <- c("economic opportunity", "innovation economy", "economic growth", "opportunity", "economy", "innovation", "growth")
```

```{r}
#Socioemotional - nonprofit
community_freq_n <- sum(sapply(community, function(word) grepl(word, nonprofit)))
dei_freq_n <- sum(sapply(dei, function(word) grepl(word, nonprofit)))
personal_growth_freq_n <- sum(sapply(personal_growth, function(word) grepl(word, nonprofit)))

cat("Community Frequency:", community_freq_n, "\n")
cat("Community Ratio:", community_freq_n/3189, "\n")
cat("DEI Frequency:", dei_freq_n, "\n")
cat("DEI Ratio:", dei_freq_n/3189, "\n")
cat("Personal Growth Frequency:", personal_growth_freq_n, "\n")
cat("Personal Growth Ratio:", personal_growth_freq_n/3189, "\n")
```

```{r}
#Socioemotional - commercial
community_freq_c <- sum(sapply(community, function(word) grepl(word, commercial)))
dei_freq_c <- sum(sapply(dei, function(word) grepl(word, commercial)))
personal_growth_freq_c <- sum(sapply(personal_growth, function(word) grepl(word, commercial)))

cat("Community Frequency:", community_freq_c, "\n")
cat("Community Ratio:", community_freq_c/3461, "\n")
cat("DEI Frequency:", dei_freq_c, "\n")
cat("DEI Ratio:", dei_freq_c/3461, "\n")
cat("Personal Growth Frequency:", personal_growth_freq_c, "\n")
cat("Personal Growth Ratio:", personal_growth_freq_c/3461, "\n")
```

```{r}
#Instrumental - nonprofit
creativity_freq_n <- sum(sapply(creativity, function(word) grepl(word, nonprofit)))
skills_freq_n <- sum(sapply(skills, function(word) grepl(word, nonprofit)))
entrepreneurship_freq_n <- sum(sapply(entrepreneurship, function(word) grepl(word, nonprofit)))
prototype_freq_n <- sum(sapply(prototype, function(word) grepl(word, nonprofit)))
economy_freq_n <- sum(sapply(economy, function(word) grepl(word, nonprofit)))

cat("Creativity Frequency:", creativity_freq_n, "\n")
cat("Creativity Ratio:", creativity_freq_n/3189, "\n")
cat("Skills Frequency:", skills_freq_n, "\n")
cat("Skills Ratio:", skills_freq_n/3189, "\n")
cat("Entrepreneurship Frequency:", entrepreneurship_freq_n, "\n")
cat("Entrepreneurship Ratio:", entrepreneurship_freq_n/3189, "\n")
cat("Prototype Frequency:", prototype_freq_n, "\n")
cat("Prototype Ratio:", prototype_freq_n/3189, "\n")
cat("Economy Frequency:", economy_freq_n, "\n")
cat("Economy Ratio:", economy_freq_n/3189, "\n")
```
```{r}
#Instrumental - commercial
creativity_freq_c <- sum(sapply(creativity, function(word) grepl(word, commercial)))
skills_freq_c <- sum(sapply(skills, function(word) grepl(word, commercial)))
entrepreneurship_freq_c <- sum(sapply(entrepreneurship, function(word) grepl(word, commercial)))
prototype_freq_c <- sum(sapply(prototype, function(word) grepl(word, commercial)))
economy_freq_c <- sum(sapply(economy, function(word) grepl(word, commercial)))

cat("Creativity Frequency:", creativity_freq_c, "\n")
cat("Creativity Ratio:", creativity_freq_c/3461, "\n")
cat("Skills Frequency:", skills_freq_c, "\n")
cat("Skills Ratio:", skills_freq_c/3461, "\n")
cat("Entrepreneurship Frequency:", entrepreneurship_freq_c, "\n")
cat("Entrepreneurship Ratio:", entrepreneurship_freq_c/3461, "\n")
cat("Prototype Frequency:", prototype_freq_c, "\n")
cat("Prototype Ratio:", prototype_freq_c/3461, "\n")
cat("Economy Frequency:", economy_freq_c, "\n")
cat("Economy Ratio:", economy_freq_c/3461, "\n")
```

```{r}
library(ggplot2)
library(tidyr)

plot_df <- data.frame(Type=c("Nonprofit", "Commercial"), Community=c(210, 145), DEI=c(57, 44), Personal_Growth=c(61, 40), Creativity=c(62, 69), Skills=c(78, 78), Entrepreneurship=c(58, 66), Prototype=c(4, 11), Economy=c(82, 50)) 

plot_df_long <- gather(plot_df, key = "Category", value = "Frequency", -Type)

ggplot(plot_df_long, aes(x = Category, y = Frequency, fill = Type)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.8) +
  labs(title = "Frequency for Socioemotional and Instrumental Coding",
       x = "Category",
       y = "Frequency") +
  scale_fill_manual(values = c("blue", "purple"), name = "Type") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r}
plot_df <- data.frame(Type=c("Nonprofit", "Commercial"), Community=c(0.066, 0.042), DEI=c(0.018, 0.013), Personal_Growth=c(0.019, 0.012), Creativity=c(0.019, 0.02), Skills=c(0.024, 0.023), Entrepreneurship=c(0.018, 0.019), Prototype=c(0.001, 0.003), Economy=c(0.009, 0.005)) 

plot_df_long <- gather(plot_df, key = "Category", value = "Ratio", -Type)

ggplot(plot_df_long, aes(x = Category, y = Ratio, fill = Type)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.8) +
  labs(title = "Ratio for Socioemotional and Instrumental Coding",
       x = "Category",
       y = "Ratio") +
  scale_fill_manual(values = c("blue", "purple"), name = "Type") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```

